# Generated by Django 2.1.7 on 2019-06-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timeStarted', models.DateTimeField(auto_now_add=True)),
                ('timeFinish', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todos.Task'),
        ),
    ]
